export const custoMatriz: (number | null)[][] = [
    [null,  40,     54,     40,     90,     30,     105,    null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [40,    null,   null,   20,     null,   25,     null,   null,   null,   null,   null,   null,   42,     null,   null,   null,   null,   null,   null,   null],
    [54,    null,   null,   null,   null,   null,   null,   20,     20,     44,     25,     null,   null,   null,   null,   null,   null,   null,   null,   null],
    [40,    20,     null,   null,   null,   null,   null,   null,   null,   null,   null,   10,     15,     null,   null,   null,   null,   null,   null,   null],
    [90,    null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [30,    25,     null,   null,   null,   null,   null,   60,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [105,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   40,     null,   null,   62,     36,     null,   null,   null],
    [null,  null,   20,     null,   null,   60,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  null,   20,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  null,   44,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  null,   25,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  null,   null,   10,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  42,     null,   15,     null,   null,   40,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   120,    30,     null,   70,     25,     297 ],
    [null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   120,    null,   null,   null,   null,   null,   null],
    [null,  null,   null,   null,   null,   null,   62,     null,   null,   null,   null,   null,   null,   30,     null,   null,   null,   null,   null,   null],
    [null,  null,   null,   null,   null,   null,   36,     null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
    [null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   70,     null,   null,   null,   null,   null,   null],
    [null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   25,     null,   null,   null,   null,   null,   null],
    [null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   297,    null,   null,   null,   null,   null,   null],
];